parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Ldap\Ldap:
        arguments: [ '@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter' ]
        tags:
            - ldap

    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - host: atc-dc02-fs
              port: 389
              options:
                  protocol_version: 3
                  referrals: false

    App\Security\UserProvider:
        arguments:
            $ldap: '@Symfony\Component\Ldap\Ldap'
            $baseDn: '%env(resolve:LDAP_BASE_DN)%'
            $searchDn: '%env(resolve:LDAP_SEARCH_DN)%'
            $searchPassword: '%env(LDAP_SEARCH_PASSWORD)%'
            $roles:
                ROLE_ADMIN: 'AtcUsersAppGroup_MaterialInventory_Admin'
                ROLE_STORE_KEEPER: 'AtcUsersAppGroup_MaterialInventory_StoreKeeper'
                ROLE_GRAPHIC_DESIGNER: 'AtcUsersAppGroup_MaterialInventory_GraphicDesigner'
            $mailAttr: 'mail' # email attribute name in the LDAP
            $displayNameAttr: 'name' # display name attribute in the LDAP
            #$extraAttributes: ['telephoneNumber']
